apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: localstack
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - name: localstack
  template:
    metadata:
      name: localstack
      namespace: argocd
      labels:
        app.kubernetes.io/name: localstack
        app.kubernetes.io/component: aws-emulation
    spec:
      project: back-stack
      source:
        repoURL: https://helm.localstack.cloud
        targetRevision: 0.7.0
        chart: localstack
        helm:
          releaseName: localstack
          values: |
            serviceAccount:
              create: true
            rbac:
              create: true
            persistence:
              enabled: true
            service:
              type: ClusterIP
              port: 4566
      destination:
        server: https://kubernetes.default.svc
        namespace: localstack
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m